package com.doubleDs.order.dao.slave.mapper;

import com.doubleDs.order.dao.slave.dto.OrderInfoHistory;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderInfoHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbg.generated Thu Nov 07 16:22:11 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbg.generated Thu Nov 07 16:22:11 CST 2019
     */
    int insert(OrderInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbg.generated Thu Nov 07 16:22:11 CST 2019
     */
    OrderInfoHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbg.generated Thu Nov 07 16:22:11 CST 2019
     */
    List<OrderInfoHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_history
     *
     * @mbg.generated Thu Nov 07 16:22:11 CST 2019
     */
    int updateByPrimaryKey(OrderInfoHistory record);

    /**
     * 转移数据到历史表
     * @param moveOrderNoList
     * @return
     */
    int insertAllOrderToHis(@Param("moveOrderNoList") List<String> moveOrderNoList);
}