package com.doubleDs.order.dao.master.dto;

import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.platform_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.platform_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String platformName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shop_Id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shop_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.inner_Order_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String innerOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.rece_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String receName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.rece_Address
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String receAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.rece_Mobile
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String receMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer payFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.express_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer expressFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.item_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer itemDiscountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer orderDiscountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.plat_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer platDiscountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.other_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer otherFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_Type
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_PayOnDelivery
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer isPayondelivery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_Create
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.logistics_way
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String logisticsWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.logistics_Company
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String logisticsCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.logistics_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String logisticsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_Cancelled
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer isCancelled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_cancel_audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer isCancelAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_Audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer isAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_Reissue
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer isReissue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.audit_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long auditPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_Audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Date gmtAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.rece_area_name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String receAreaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.member_Code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long memberCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.sku_Kind
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer skuKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.sku_Num
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer skuNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.remark
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer discountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.cancel_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long cancelPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_Cancel
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Date gmtCancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.nullity_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long nullityPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_nullity
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Date gmtNullity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.creator
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_express
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Date gmtExpress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_Complete
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Date gmtComplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.merchant_code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String merchantCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_pay_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Long orderPayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.audit_Reason
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String auditReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_valid
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.record_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer recordStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.retry_erp_count
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer retryErpCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.out_order_no
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String outOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.cancel_reason
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String cancelReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.lng
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.lat
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_time
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.actual_cash_desk_amount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer actualCashDeskAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.source
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_index
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer orderIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_time_end
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Date deliveryTimeEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.packing_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer packingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_discount_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer totalDiscountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.send_mw_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer sendMwStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.account_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer accountStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.excep_type
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String excepType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.remind_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer remindStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.remind_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String remindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.box_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer boxFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.delivery_discount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private String deliveryDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.all_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer allPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_freight_money
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer orderFreightMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.sale_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_buyer_payable_money
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer orderBuyerPayableMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.settlement_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer settlementPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.commission
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_need_pick_up_code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Boolean isNeedPickUpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.all_cost_amount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer allCostAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.erp_push_num
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer erpPushNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_Pushed
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    private Integer isPushed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.platform_id
     *
     * @return the value of order_info.platform_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.platform_id
     *
     * @param platformId the value for order_info.platform_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.platform_Name
     *
     * @return the value of order_info.platform_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getPlatformName() {
        return platformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.platform_Name
     *
     * @param platformName the value for order_info.platform_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setPlatformName(String platformName) {
        this.platformName = platformName == null ? null : platformName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shop_Id
     *
     * @return the value of order_info.shop_Id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shop_Id
     *
     * @param shopId the value for order_info.shop_Id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shop_Name
     *
     * @return the value of order_info.shop_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shop_Name
     *
     * @param shopName the value for order_info.shop_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_No
     *
     * @return the value of order_info.order_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_No
     *
     * @param orderNo the value for order_info.order_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.inner_Order_No
     *
     * @return the value of order_info.inner_Order_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getInnerOrderNo() {
        return innerOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.inner_Order_No
     *
     * @param innerOrderNo the value for order_info.inner_Order_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setInnerOrderNo(String innerOrderNo) {
        this.innerOrderNo = innerOrderNo == null ? null : innerOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.rece_Name
     *
     * @return the value of order_info.rece_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getReceName() {
        return receName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.rece_Name
     *
     * @param receName the value for order_info.rece_Name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setReceName(String receName) {
        this.receName = receName == null ? null : receName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.rece_Address
     *
     * @return the value of order_info.rece_Address
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getReceAddress() {
        return receAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.rece_Address
     *
     * @param receAddress the value for order_info.rece_Address
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setReceAddress(String receAddress) {
        this.receAddress = receAddress == null ? null : receAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.rece_Mobile
     *
     * @return the value of order_info.rece_Mobile
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getReceMobile() {
        return receMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.rece_Mobile
     *
     * @param receMobile the value for order_info.rece_Mobile
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setReceMobile(String receMobile) {
        this.receMobile = receMobile == null ? null : receMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_Fee
     *
     * @return the value of order_info.total_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_Fee
     *
     * @param totalFee the value for order_info.total_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_Fee
     *
     * @return the value of order_info.pay_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getPayFee() {
        return payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_Fee
     *
     * @param payFee the value for order_info.pay_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setPayFee(Integer payFee) {
        this.payFee = payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.express_Fee
     *
     * @return the value of order_info.express_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getExpressFee() {
        return expressFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.express_Fee
     *
     * @param expressFee the value for order_info.express_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setExpressFee(Integer expressFee) {
        this.expressFee = expressFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.item_Discount_Fee
     *
     * @return the value of order_info.item_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getItemDiscountFee() {
        return itemDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.item_Discount_Fee
     *
     * @param itemDiscountFee the value for order_info.item_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setItemDiscountFee(Integer itemDiscountFee) {
        this.itemDiscountFee = itemDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_Discount_Fee
     *
     * @return the value of order_info.order_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getOrderDiscountFee() {
        return orderDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_Discount_Fee
     *
     * @param orderDiscountFee the value for order_info.order_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOrderDiscountFee(Integer orderDiscountFee) {
        this.orderDiscountFee = orderDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.plat_Discount_Fee
     *
     * @return the value of order_info.plat_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getPlatDiscountFee() {
        return platDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.plat_Discount_Fee
     *
     * @param platDiscountFee the value for order_info.plat_Discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setPlatDiscountFee(Integer platDiscountFee) {
        this.platDiscountFee = platDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.other_Fee
     *
     * @return the value of order_info.other_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getOtherFee() {
        return otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.other_Fee
     *
     * @param otherFee the value for order_info.other_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOtherFee(Integer otherFee) {
        this.otherFee = otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_Type
     *
     * @return the value of order_info.order_Type
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_Type
     *
     * @param orderType the value for order_info.order_Type
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_PayOnDelivery
     *
     * @return the value of order_info.is_PayOnDelivery
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getIsPayondelivery() {
        return isPayondelivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_PayOnDelivery
     *
     * @param isPayondelivery the value for order_info.is_PayOnDelivery
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setIsPayondelivery(Integer isPayondelivery) {
        this.isPayondelivery = isPayondelivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_Create
     *
     * @return the value of order_info.gmt_Create
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_Create
     *
     * @param gmtCreate the value for order_info.gmt_Create
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.logistics_way
     *
     * @return the value of order_info.logistics_way
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getLogisticsWay() {
        return logisticsWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.logistics_way
     *
     * @param logisticsWay the value for order_info.logistics_way
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setLogisticsWay(String logisticsWay) {
        this.logisticsWay = logisticsWay == null ? null : logisticsWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.logistics_Company
     *
     * @return the value of order_info.logistics_Company
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getLogisticsCompany() {
        return logisticsCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.logistics_Company
     *
     * @param logisticsCompany the value for order_info.logistics_Company
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setLogisticsCompany(String logisticsCompany) {
        this.logisticsCompany = logisticsCompany == null ? null : logisticsCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.logistics_No
     *
     * @return the value of order_info.logistics_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getLogisticsNo() {
        return logisticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.logistics_No
     *
     * @param logisticsNo the value for order_info.logistics_No
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setLogisticsNo(String logisticsNo) {
        this.logisticsNo = logisticsNo == null ? null : logisticsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_Cancelled
     *
     * @return the value of order_info.is_Cancelled
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getIsCancelled() {
        return isCancelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_Cancelled
     *
     * @param isCancelled the value for order_info.is_Cancelled
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setIsCancelled(Integer isCancelled) {
        this.isCancelled = isCancelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_cancel_audit
     *
     * @return the value of order_info.is_cancel_audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getIsCancelAudit() {
        return isCancelAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_cancel_audit
     *
     * @param isCancelAudit the value for order_info.is_cancel_audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setIsCancelAudit(Integer isCancelAudit) {
        this.isCancelAudit = isCancelAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_Audit
     *
     * @return the value of order_info.is_Audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_Audit
     *
     * @param isAudit the value for order_info.is_Audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setIsAudit(Integer isAudit) {
        this.isAudit = isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_Reissue
     *
     * @return the value of order_info.is_Reissue
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getIsReissue() {
        return isReissue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_Reissue
     *
     * @param isReissue the value for order_info.is_Reissue
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setIsReissue(Integer isReissue) {
        this.isReissue = isReissue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.audit_Person
     *
     * @return the value of order_info.audit_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getAuditPerson() {
        return auditPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.audit_Person
     *
     * @param auditPerson the value for order_info.audit_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setAuditPerson(Long auditPerson) {
        this.auditPerson = auditPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_Audit
     *
     * @return the value of order_info.gmt_Audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Date getGmtAudit() {
        return gmtAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_Audit
     *
     * @param gmtAudit the value for order_info.gmt_Audit
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setGmtAudit(Date gmtAudit) {
        this.gmtAudit = gmtAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.rece_area_name
     *
     * @return the value of order_info.rece_area_name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getReceAreaName() {
        return receAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.rece_area_name
     *
     * @param receAreaName the value for order_info.rece_area_name
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setReceAreaName(String receAreaName) {
        this.receAreaName = receAreaName == null ? null : receAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.member_Code
     *
     * @return the value of order_info.member_Code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getMemberCode() {
        return memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.member_Code
     *
     * @param memberCode the value for order_info.member_Code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setMemberCode(Long memberCode) {
        this.memberCode = memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.sku_Kind
     *
     * @return the value of order_info.sku_Kind
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getSkuKind() {
        return skuKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.sku_Kind
     *
     * @param skuKind the value for order_info.sku_Kind
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setSkuKind(Integer skuKind) {
        this.skuKind = skuKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.sku_Num
     *
     * @return the value of order_info.sku_Num
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getSkuNum() {
        return skuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.sku_Num
     *
     * @param skuNum the value for order_info.sku_Num
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setSkuNum(Integer skuNum) {
        this.skuNum = skuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.remark
     *
     * @return the value of order_info.remark
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.remark
     *
     * @param remark the value for order_info.remark
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.discount_Fee
     *
     * @return the value of order_info.discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.discount_Fee
     *
     * @param discountFee the value for order_info.discount_Fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setDiscountFee(Integer discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.cancel_Person
     *
     * @return the value of order_info.cancel_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getCancelPerson() {
        return cancelPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.cancel_Person
     *
     * @param cancelPerson the value for order_info.cancel_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setCancelPerson(Long cancelPerson) {
        this.cancelPerson = cancelPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_Cancel
     *
     * @return the value of order_info.gmt_Cancel
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Date getGmtCancel() {
        return gmtCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_Cancel
     *
     * @param gmtCancel the value for order_info.gmt_Cancel
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setGmtCancel(Date gmtCancel) {
        this.gmtCancel = gmtCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.nullity_Person
     *
     * @return the value of order_info.nullity_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getNullityPerson() {
        return nullityPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.nullity_Person
     *
     * @param nullityPerson the value for order_info.nullity_Person
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setNullityPerson(Long nullityPerson) {
        this.nullityPerson = nullityPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_nullity
     *
     * @return the value of order_info.gmt_nullity
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Date getGmtNullity() {
        return gmtNullity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_nullity
     *
     * @param gmtNullity the value for order_info.gmt_nullity
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setGmtNullity(Date gmtNullity) {
        this.gmtNullity = gmtNullity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.creator
     *
     * @return the value of order_info.creator
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.creator
     *
     * @param creator the value for order_info.creator
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_express
     *
     * @return the value of order_info.gmt_express
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Date getGmtExpress() {
        return gmtExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_express
     *
     * @param gmtExpress the value for order_info.gmt_express
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setGmtExpress(Date gmtExpress) {
        this.gmtExpress = gmtExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_Complete
     *
     * @return the value of order_info.gmt_Complete
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Date getGmtComplete() {
        return gmtComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_Complete
     *
     * @param gmtComplete the value for order_info.gmt_Complete
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setGmtComplete(Date gmtComplete) {
        this.gmtComplete = gmtComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.merchant_code
     *
     * @return the value of order_info.merchant_code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.merchant_code
     *
     * @param merchantCode the value for order_info.merchant_code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_pay_id
     *
     * @return the value of order_info.order_pay_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Long getOrderPayId() {
        return orderPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_pay_id
     *
     * @param orderPayId the value for order_info.order_pay_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOrderPayId(Long orderPayId) {
        this.orderPayId = orderPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.audit_Reason
     *
     * @return the value of order_info.audit_Reason
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getAuditReason() {
        return auditReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.audit_Reason
     *
     * @param auditReason the value for order_info.audit_Reason
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setAuditReason(String auditReason) {
        this.auditReason = auditReason == null ? null : auditReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_valid
     *
     * @return the value of order_info.is_valid
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_valid
     *
     * @param isValid the value for order_info.is_valid
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.record_status
     *
     * @return the value of order_info.record_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.record_status
     *
     * @param recordStatus the value for order_info.record_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.retry_erp_count
     *
     * @return the value of order_info.retry_erp_count
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getRetryErpCount() {
        return retryErpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.retry_erp_count
     *
     * @param retryErpCount the value for order_info.retry_erp_count
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setRetryErpCount(Integer retryErpCount) {
        this.retryErpCount = retryErpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.out_order_no
     *
     * @return the value of order_info.out_order_no
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getOutOrderNo() {
        return outOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.out_order_no
     *
     * @param outOrderNo the value for order_info.out_order_no
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOutOrderNo(String outOrderNo) {
        this.outOrderNo = outOrderNo == null ? null : outOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.cancel_reason
     *
     * @return the value of order_info.cancel_reason
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.cancel_reason
     *
     * @param cancelReason the value for order_info.cancel_reason
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.lng
     *
     * @return the value of order_info.lng
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.lng
     *
     * @param lng the value for order_info.lng
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.lat
     *
     * @return the value of order_info.lat
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.lat
     *
     * @param lat the value for order_info.lat
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_time
     *
     * @return the value of order_info.delivery_time
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_time
     *
     * @param deliveryTime the value for order_info.delivery_time
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.actual_cash_desk_amount
     *
     * @return the value of order_info.actual_cash_desk_amount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getActualCashDeskAmount() {
        return actualCashDeskAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.actual_cash_desk_amount
     *
     * @param actualCashDeskAmount the value for order_info.actual_cash_desk_amount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setActualCashDeskAmount(Integer actualCashDeskAmount) {
        this.actualCashDeskAmount = actualCashDeskAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.source
     *
     * @return the value of order_info.source
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.source
     *
     * @param source the value for order_info.source
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_index
     *
     * @return the value of order_info.order_index
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_index
     *
     * @param orderIndex the value for order_info.order_index
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_time_end
     *
     * @return the value of order_info.delivery_time_end
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Date getDeliveryTimeEnd() {
        return deliveryTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_time_end
     *
     * @param deliveryTimeEnd the value for order_info.delivery_time_end
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setDeliveryTimeEnd(Date deliveryTimeEnd) {
        this.deliveryTimeEnd = deliveryTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.packing_fee
     *
     * @return the value of order_info.packing_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getPackingFee() {
        return packingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.packing_fee
     *
     * @param packingFee the value for order_info.packing_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setPackingFee(Integer packingFee) {
        this.packingFee = packingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_discount_fee
     *
     * @return the value of order_info.total_discount_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getTotalDiscountFee() {
        return totalDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_discount_fee
     *
     * @param totalDiscountFee the value for order_info.total_discount_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setTotalDiscountFee(Integer totalDiscountFee) {
        this.totalDiscountFee = totalDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_status
     *
     * @return the value of order_info.pay_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_status
     *
     * @param payStatus the value for order_info.pay_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.send_mw_status
     *
     * @return the value of order_info.send_mw_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getSendMwStatus() {
        return sendMwStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.send_mw_status
     *
     * @param sendMwStatus the value for order_info.send_mw_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setSendMwStatus(Integer sendMwStatus) {
        this.sendMwStatus = sendMwStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.account_status
     *
     * @return the value of order_info.account_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.account_status
     *
     * @param accountStatus the value for order_info.account_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.excep_type
     *
     * @return the value of order_info.excep_type
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getExcepType() {
        return excepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.excep_type
     *
     * @param excepType the value for order_info.excep_type
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setExcepType(String excepType) {
        this.excepType = excepType == null ? null : excepType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.remind_status
     *
     * @return the value of order_info.remind_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getRemindStatus() {
        return remindStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.remind_status
     *
     * @param remindStatus the value for order_info.remind_status
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setRemindStatus(Integer remindStatus) {
        this.remindStatus = remindStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.remind_id
     *
     * @return the value of order_info.remind_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getRemindId() {
        return remindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.remind_id
     *
     * @param remindId the value for order_info.remind_id
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setRemindId(String remindId) {
        this.remindId = remindId == null ? null : remindId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.box_fee
     *
     * @return the value of order_info.box_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getBoxFee() {
        return boxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.box_fee
     *
     * @param boxFee the value for order_info.box_fee
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setBoxFee(Integer boxFee) {
        this.boxFee = boxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.delivery_discount
     *
     * @return the value of order_info.delivery_discount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public String getDeliveryDiscount() {
        return deliveryDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.delivery_discount
     *
     * @param deliveryDiscount the value for order_info.delivery_discount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setDeliveryDiscount(String deliveryDiscount) {
        this.deliveryDiscount = deliveryDiscount == null ? null : deliveryDiscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.all_price
     *
     * @return the value of order_info.all_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getAllPrice() {
        return allPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.all_price
     *
     * @param allPrice the value for order_info.all_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setAllPrice(Integer allPrice) {
        this.allPrice = allPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_freight_money
     *
     * @return the value of order_info.order_freight_money
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getOrderFreightMoney() {
        return orderFreightMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_freight_money
     *
     * @param orderFreightMoney the value for order_info.order_freight_money
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOrderFreightMoney(Integer orderFreightMoney) {
        this.orderFreightMoney = orderFreightMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.sale_price
     *
     * @return the value of order_info.sale_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.sale_price
     *
     * @param salePrice the value for order_info.sale_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setSalePrice(Integer salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_buyer_payable_money
     *
     * @return the value of order_info.order_buyer_payable_money
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getOrderBuyerPayableMoney() {
        return orderBuyerPayableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_buyer_payable_money
     *
     * @param orderBuyerPayableMoney the value for order_info.order_buyer_payable_money
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setOrderBuyerPayableMoney(Integer orderBuyerPayableMoney) {
        this.orderBuyerPayableMoney = orderBuyerPayableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.settlement_price
     *
     * @return the value of order_info.settlement_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.settlement_price
     *
     * @param settlementPrice the value for order_info.settlement_price
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setSettlementPrice(Integer settlementPrice) {
        this.settlementPrice = settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.commission
     *
     * @return the value of order_info.commission
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.commission
     *
     * @param commission the value for order_info.commission
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setCommission(Integer commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_need_pick_up_code
     *
     * @return the value of order_info.is_need_pick_up_code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Boolean getIsNeedPickUpCode() {
        return isNeedPickUpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_need_pick_up_code
     *
     * @param isNeedPickUpCode the value for order_info.is_need_pick_up_code
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setIsNeedPickUpCode(Boolean isNeedPickUpCode) {
        this.isNeedPickUpCode = isNeedPickUpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.all_cost_amount
     *
     * @return the value of order_info.all_cost_amount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getAllCostAmount() {
        return allCostAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.all_cost_amount
     *
     * @param allCostAmount the value for order_info.all_cost_amount
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setAllCostAmount(Integer allCostAmount) {
        this.allCostAmount = allCostAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.erp_push_num
     *
     * @return the value of order_info.erp_push_num
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getErpPushNum() {
        return erpPushNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.erp_push_num
     *
     * @param erpPushNum the value for order_info.erp_push_num
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setErpPushNum(Integer erpPushNum) {
        this.erpPushNum = erpPushNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_Pushed
     *
     * @return the value of order_info.is_Pushed
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public Integer getIsPushed() {
        return isPushed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_Pushed
     *
     * @param isPushed the value for order_info.is_Pushed
     *
     * @mbg.generated Thu Nov 07 16:09:01 CST 2019
     */
    public void setIsPushed(Integer isPushed) {
        this.isPushed = isPushed;
    }
}